# Generated by Django 5.1 on 2024-08-10 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pendiente'), ('In Progress', 'En progreso'), ('Completed', 'Completado')], default='Pending', max_length=50)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals_app.goal')),
            ],
        ),
    ]
